name: checks
on:
  push:
jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install requests
      - run: python check_links.py || python check_links.py || python check_links.py
